[build]
  command = "npm run build"
  publish = ".next"

# This tells Netlify to use the Next.js runtime,
# which handles features like server-side rendering, image optimization, etc.
# It's often auto-detected, but explicitly adding it can be beneficial.
[[plugins]]
  package = "@netlify/plugin-nextjs"
